In [1]:
import numpy as np
import matplotlib.pyplot as plt
from asa.dataset import Dataset

# get data by name

In [2]:
x = np.random.normal(size=1000)
y = x**2 + np.random.normal(size=1000)
z = np.log(np.abs(x + y)) + np.random.normal(size=1000)

In [3]:
data = np.array([x, y, z]).T

In [4]:
dataset = Dataset(data, ['x', 'y', 'z'], ['x', 'y', 'z'])

In [5]:
np.array_equal(dataset['x'], x)

True

In [8]:
np.array_equal(dataset[['x', 'y']], np.array([x, y]).T)

True

You can also use index

In [9]:
np.array_equal(dataset[:, 0], x)

True

In [10]:
np.array_equal(dataset[3:5, 'x'], x[3:5])

True

# summary

In [2]:
x = np.random.normal(size=1000)
y = x**2 + np.random.normal(size=1000)
z = np.log(np.abs(x + y)) + np.random.normal(size=1000)

In [3]:
data = np.array([x, y, z]).T

In [4]:
dataset = Dataset(data, ['x', 'y', 'z'], ['x', 'y', 'z'])

In [5]:
dataset

Dataset summary:
  Data shape: (1000, 3)
  Names: ['x' 'y' 'z']
  Labels: ['x' 'y' 'z']

In [6]:
print(dataset)

Dataset summary:
  Data shape: (1000, 3)
  Names: ['x' 'y' 'z']
  Labels: ['x' 'y' 'z']



In [7]:
dataset.summary()

Dataset summary:
  Data shape: (1000, 3)
  Names: ['x' 'y' 'z']
  Labels: ['x' 'y' 'z']



## add col

In [2]:
x = np.random.normal(size=1000)
y = x**2 + np.random.normal(size=1000)
z = np.log(np.abs(x + y)) + np.random.normal(size=1000)

In [3]:
data = np.array([x, y, z]).T

In [4]:
dataset = Dataset(data, ['x', 'y', 'z'], ['x', 'y', 'z'])

In [5]:
x2 = np.random.normal(size=1000)
y2 = 5 * x2

data2 = np.array([x2, y2]).T

In [6]:
dataset.data

array([[ 0.64752731, -1.31300452,  0.2137069 ],
       [ 0.09148521,  1.61166788,  1.84197595],
       [ 0.50367596, -0.29187804, -2.39552293],
       ...,
       [ 0.22938337,  0.22512375, -2.47035708],
       [ 0.07059287, -0.59716585,  1.00362176],
       [ 0.83279267,  0.32367676, -0.72838908]])

In [7]:
dataset.add_col(data2, ['x2', 'y2'], ['x2', 'y2'])

In [8]:
dataset.data

array([[ 0.64752731, -1.31300452,  0.2137069 ,  0.22499712,  1.12498561],
       [ 0.09148521,  1.61166788,  1.84197595, -0.19023504, -0.95117522],
       [ 0.50367596, -0.29187804, -2.39552293,  0.6540276 ,  3.27013802],
       ...,
       [ 0.22938337,  0.22512375, -2.47035708,  0.3555661 ,  1.77783051],
       [ 0.07059287, -0.59716585,  1.00362176,  1.0756507 ,  5.37825351],
       [ 0.83279267,  0.32367676, -0.72838908,  1.56996442,  7.84982208]])

In [9]:
dataset.labels

array(['x', 'y', 'z', 'x2', 'y2'], dtype='<U2')

In [10]:
dataset.names

array(['x', 'y', 'z', 'x2', 'y2'], dtype='<U2')

In [11]:
dataset.add_col(x2, 'x3', 'x3')

In [12]:
dataset.data

array([[ 0.64752731, -1.31300452,  0.2137069 ,  0.22499712,  1.12498561,
         0.22499712],
       [ 0.09148521,  1.61166788,  1.84197595, -0.19023504, -0.95117522,
        -0.19023504],
       [ 0.50367596, -0.29187804, -2.39552293,  0.6540276 ,  3.27013802,
         0.6540276 ],
       ...,
       [ 0.22938337,  0.22512375, -2.47035708,  0.3555661 ,  1.77783051,
         0.3555661 ],
       [ 0.07059287, -0.59716585,  1.00362176,  1.0756507 ,  5.37825351,
         1.0756507 ],
       [ 0.83279267,  0.32367676, -0.72838908,  1.56996442,  7.84982208,
         1.56996442]])

In [13]:
dataset.names

array(['x', 'y', 'z', 'x2', 'y2', 'x3'], dtype='<U2')

## add row

In [13]:
x = np.random.normal(size=2)
y = x**2 + np.random.normal(size=2)
z = np.log(np.abs(x + y)) + np.random.normal(size=2)

data = np.array([x, y, z]).T

In [14]:
dataset = Dataset(data, ['x', 'y', 'z'], ['x', 'y', 'z'])

In [15]:
dataset.data

array([[-0.40582594, -0.56467297, -0.72744638],
       [-1.0174954 ,  1.09714111, -2.71158197]])

In [16]:
dataset.add_row(data)

In [17]:
dataset.data

array([[-0.40582594, -0.56467297, -0.72744638],
       [-1.0174954 ,  1.09714111, -2.71158197],
       [-0.40582594, -0.56467297, -0.72744638],
       [-1.0174954 ,  1.09714111, -2.71158197]])